server {

    server_name wallet.example.com;
    include /etc/nginx/snippets/cloudflare-ips.conf;

    listen 443 ssl;
    listen [::]:443 ssl;
    ssl_certificate /etc/letsencrypt/live/wallet.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wallet.example.com/privkey.pem;

    root /var/www/the-wallet/release;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /manifest.webmanifest {
        add_header Cache-Control "no-cache";
    }

    location ~* \.(?:js|css|png|jpg|jpeg|gif|svg|ico|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

}
server {
    if ($host = wallet.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    listen [::]:80;

    server_name wallet.example.com;
    include /etc/nginx/snippets/cloudflare-ips.conf;
    return 404; # managed by Certbot

}